services:
  task-app:
    container_name: task-manager-container
    build:
      context: .
      args:
        JWT_SECRET_KEY: ${JWT_SECRET_KEY}
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    restart: always
    depends_on:
      - redis
    environment:
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
  redis:
    container_name: redis-container
    image: redis
    restart: always
    ports:
      - 6379:6379